### ISSUE TITLE
cookies loaded but login page detected

### ISSUE THREAD

**Issue by evilsh3ll** [s0rg/crawley#51]
Hello, when I use this command:
```crawley -depth -1 -dirs only -cookie "phpbb3_XXXXXX_sid=XXXXXX; phpbb3_XXXXXX_u=XXXXXX; phpbb3_XXXXXX_k=XXXXXX;" "https://XXXXXX.net/viewtopic.php?p=5018859" > urls.txt```
crawley scrapes the login page of the forum and not the thread I selected, crawley doesn't return any errors
```
2023/03/20 16:08:58 [*] config: workers: 4 depth: -1 delay: 150ms
2023/03/20 16:08:58 [*] crawling url: https://XXXXXX.net/viewtopic.php?p=5018859
2023/03/20 16:09:00 [*] complete
```
I tried with different user agents and headers, every time the result is the same: login page of the forum. The cookies are ok, I copied them using EditThisCookie googlechrome extension. I'm not using any vpn/proxy.
**I tested also other forums, the result is always the same, I can't login.**
Do you know if there is a problem loading cookies?

**Comment by s0rg** [comment]
i failed to register at ddunlimited.net, as long as i cant speak italian, so i cannot understand questions. I can try to help you with this issue, but i need credentials (and urls) for testing. Can you provide them? My email is al3x.s0rg(at)gmail.com

**Comment by evilsh3ll** [comment]
ok, I created a test account with temp email, I sent you the full cookie in netscape format. I just tested the cookie in two different browsers, it works.

**Comment by s0rg** [comment]
Ok, you need to use "Semicolon separated Cookie File" format upon export, and rigth now you also need to manauly remove all comments from result. I will add coments parsing in future releases, this is the first encounter )

**Comment by evilsh3ll** [comment]
I exported cookies from EditThisCookie extension using the "semicolon separeted format", I removed the first 3 comment lines but it's again in the login page.
This is the exported string (it's almost the same I manually built in the previous tests 🥲):
![image](https://user-images.githubusercontent.com/63223659/226450296-1bfdd403-bffd-4833-8651-05412c36161a.png)

**Comment by evilsh3ll** [comment]
I get these 48 links (as before when I set -headless without -dirs only) https://bin.disroot.org/?6bf486611c974dc6#BFLGkPZatknTvchGpe1UQbofmhZ4ToCR7RbHw3G4Eihb that are the parts of the login page because there is the button `https://ddunlimited.net/ucp.php?mode=sendpassword` "I lost password" (that is the "I lost password" button in the login page) and also the other buttons/links of the same login page.
![image](https://user-images.githubusercontent.com/63223659/226455810-0cd09973-3ec7-4154-b461-56c5fc22b72c.png) 
Instead in the page I try to scrape there should be >300 forum threads (it's a page with a huge index)

**Comment by evilsh3ll** [comment]
Any idea? Did you get more links than me?

**Comment by s0rg** [comment]
Nope, i hope i got some time to investigate this at next weekend. As for now - please try change user-agent for crawley, you need to get you current browser user-agent string (from any request) and give it crawley with `-user-agent "your-user-agent-here"` flag.

**Comment by evilsh3ll** [comment]
When you have time, do you know how to get the header string used by my browser (brave, archlinux)? I'm searching but there aren't info.

**Comment by evilsh3ll** [comment]
I found a way to make the cookies working with **curl**:
```
curl --cookie "phpbb3_ddu4final_k=XXX;phpbb3_ddu4final_sid=XXXX;phpbb3_ddu4final_u=XXXX;" -j -L "https://ddunlimited.net/viewtopic.php?f=440" -o test.html
```
using the **-j** parameter the page is correct page, this works only for this website, I don't know why.

_**New cookie session**
Instead of telling curl when a session ends, curl features an option that lets the user decide when a new session begins.
A new cookie session means that all the old session cookies will be thrown away. It is the equivalent of closing a browser and starting it up again.
Tell curl a new cookie session starts by using -j, --junk-session-cookies_

Do you know if there is a similar feature for crawley (something like cleaning all previous cookies before using the new one)?

**Comment by s0rg** [comment]
Thank you for this investigation, i will inspect this closer, an add such feature to crawley.

**Comment by s0rg** [comment]
Plese, check out new https://github.com/s0rg/crawley/releases/tag/v1.5.12 release it should fix this issue.

**Comment by evilsh3ll** [comment]
I tried again using this command:
```
crawley -depth -1 -headless -cookie "phpbb3_ddu4final_k=XXX" -cookie "phpbb3_ddu4final_sid=XXX" -cookie "phpbb3_ddu4final_u=XXX" "https://ddunlimited.net/viewtopic.php?p=5018859" > test.txt
```
getting this output:
```
Scraping all urls

2023/03/29 23:46:12 [*] config: workers: 4 depth: -1 delay: 150ms
2023/03/29 23:46:12 [*] crawling url: https://ddunlimited.net/viewtopic.php?p=5018859
2023/03/29 23:46:13 [*] complete
```
Cookies are loaded, I'm not sure if the "cleaning" feature is by default.
**Thanks for your support**
_Crawley v1.5.12-a1f6de2_ (archlinux)

**Comment by s0rg** [comment]
its by default. Thank you for your detailed reports - they are very helpfull.

**Comment by evilsh3ll** [comment]
I forgot to say that the page is still the login page, it seems cookies are not correctly loaded

**Comment by s0rg** [comment]
Hello again )
Please check out new release: https://github.com/s0rg/crawley/releases/tag/v1.5.13
Seems i fixed it )

Please note, you still need `-user-agent` to make phpbb happy:

**Comment by evilsh3ll** [comment]
```
crawley \
-headless \
-user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0' \
-cookie 'phpbb3_ddu4final_k=xxx; phpbb3_ddu4final_sid=xxx; phpbb3_ddu4final_u=xxx' \
'https://ddunlimited.net/viewtopic.php?p=5018859' > list.txt
```
output:
```
2023/04/06 00:19:00 [*] config: workers: 4 depth: 0 delay: 150ms
2023/04/06 00:19:00 [*] crawling url: https://ddunlimited.net/viewtopic.php?p=5018859
2023/04/06 00:19:05 [-] GET https://ddunlimited.net/viewtopic.php?p=5018859: Get "https://ddunlimited.net/viewtopic.php?p=5018859": context deadline exceeded
2023/04/06 00:19:05 [*] complete
```
I tried a lot of combination of paramters, I get everytime the same error above.

There is also another problem (this exact command worked with **Crawley v1.5.8-84c5855** but now it's not working anymore) :
```
crawley -headless -user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0' -cookie 'CENSORED_key=a%3A4%3A%7Bi%3A0%3Bs%3A6%3A%22153366%22%3Bi%3A1%3Bs%3A40%3A%225b6hf75839hf5832g6f4cf2%22%3Bi%3A2%3Bi%3A1868962414%3Bi%3A3%3Bi%3A0%3B%7D' 'CENSORED_URL' > list.2.txt
```
output:
```
2023/04/06 00:26:00 [*] config: workers: 4 depth: 0 delay: 150ms
2023/04/06 00:26:00 [*] crawling url: CENSORED_URL
2023/04/06 00:26:00 net/http: invalid byte ';' in Cookie.Value; dropping invalid bytes
2023/04/06 00:26:01 [*] complete
```
the cookie value doesn't include any semicolon, maybe it's an encoded value (censored key and url doesn't include semicolon)

**Comment by s0rg** [comment]
Please, check version https://github.com/s0rg/crawley/releases/tag/v1.5.14
Cookie decoding now gone, so it will load any cookie. And please keep in mind that you need to use the same user-agent, from which you obtain those cookies. So you need to copy cookies AND you user-agent from request.

**Comment by evilsh3ll** [comment]
The cookies is loading but only in https://ddunlimited.net/viewtopic.php?p=5018859 I get the **context deadline exceeded** error. I extracted my exact user-agent string and used a fresh new cookie (from the same browser) but the same error is still present.
```
2023/04/12 10:18:18 [*] config: workers: 4 depth: 0 delay: 150ms
2023/04/12 10:18:18 [*] crawling url: https://ddunlimited.net/viewtopic.php?t=3610730
2023/04/12 10:18:24 [-] GET https://ddunlimited.net/viewtopic.php?t=3610730: Get "https://ddunlimited.net/viewtopic.php?t=3610730": context deadline exceeded
2023/04/12 10:18:24 [*] complete
Time: 5 s.
```
I can't get any info online about the **context deadline exceeded** error, I don't know why if I use curl I don't get any error.

Thanks for your support

**Comment by s0rg** [comment]
Please, check fresh release: https://github.com/s0rg/crawley/releases/tag/v1.6.0 it has `-timeout` option, so you can increase default timeout (5 seconds).
